# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14-browsers

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - node14-dependencies-v2-{{ checksum "yarn.lock" }}
          # Fallback to using the latest cache if no exact match is found
          - node14-dependencies-v2-

      - run:
          name: Set up apt
          command: |
            sudo apt-get -qq update
            sudo apt-get -y -qq install apt-transport-https

      - run:
          name: Install Yarn
          command: |
            sudo rm -f /usr/local/bin/yarn
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            sudo apt-get -qq update
            # transform the '>=x.y.z' version constraint in package.json to the 'x.y.z-1' version format of apt-get
            YARN_VERSION=$( jq -r '(.engines.yarn | gsub("[^0-9.]";"")) + "-1"' < package.json )
            sudo apt-get -qq install --no-install-recommends yarn=$YARN_VERSION

      - run:
          name: Install dependencies
          command: yarn --frozen-lockfile

      - save_cache:
          paths:
            - ~/.cache/yarn
            - node_modules
          key: node14-dependencies-v2-{{ checksum "yarn.lock" }}

      # Build
      - run:
          name: Build
          command: REACT_APP_VERSION=${CIRCLE_SHA1:0:7} REACT_APP_BRANCH=$CIRCLE_BRANCH yarn build

      # Run tests
      - run:
          name: Test
          command: yarn test

      - deploy:
          command: |
            sudo apt-get -y -qq install awscli
            aws s3 sync build/ s3://vasttester-origin-$CIRCLE_BRANCH.iabtechlab.com/ --delete --cache-control max-age=300 --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
