version: 2
jobs:
  build:
    docker:
      - image: cimg/node:14.17.0
    environment:
      AWS_PAGER: ''
    steps:
      - checkout
      - run:
          name: Install AWS CLI v2
          command: |
            curl -sSL https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscliv2.zip
            unzip awscliv2.zip
            rm awscliv2.zip
            sudo aws/install
      - restore_cache:
          keys:
            - node14-dependencies-v2-{{ checksum "yarn.lock" }}
            - node14-dependencies-v2-
      - run:
          name: Install Yarn
          command: |
            # Remove preinstalled Yarn to avoid conflicts
            sudo rm -f /usr/local/bin/yarn
            # Get Yarn version from package.json and remove >= prefix
            YARN_VERSION=$( jq -r '(.engines.yarn | gsub("[^0-9.]";""))' < package.json )
            # Download and install
            curl -sSL "https://github.com/yarnpkg/yarn/releases/download/v$YARN_VERSION/yarn_${YARN_VERSION}_all.deb" -o yarn.deb
            sudo dpkg -i yarn.deb
            rm yarn.deb
      - run:
          name: Install dependencies
          command: yarn --frozen-lockfile
      - save_cache:
          paths:
            - ~/.cache/yarn
            - node_modules
          key: node14-dependencies-v2-{{ checksum "yarn.lock" }}
      - run:
          name: Build
          command: |
            export REACT_APP_VERSION=${CIRCLE_SHA1:0:7}
            export REACT_APP_BRANCH=$CIRCLE_BRANCH
            export REACT_APP_BUILD_DATE=$(TZ=GMT date +'%b %_d, %Y, %_I:%M %p %Z')
            yarn run build
      - run:
          name: Test
          command: yarn run test
      - deploy:
          name: Deploy if allowed
          command: |
            BRANCHES='master candidate release'
            if [[ " $BRANCHES " = *" $CIRCLE_BRANCH "* ]]; then
              BUCKET=vasttester-origin-$CIRCLE_BRANCH.iabtechlab.com
              echo Deploying to $BUCKET...
              aws s3 sync \
                build/ \
                s3://$BUCKET/ \
                --delete \
                --cache-control max-age=300 \
                --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
            else
              echo Not deploying $CIRCLE_BRANCH branch
            fi
